### ISSUE TITLE
statusCode: undefined

### ISSUE THREAD

**Issue by l2aelba** [transitive-bullshit/check-links#2]
Im not sure, but I got `statusCode: undefined` when the domain is not alive

```
{ status: 'dead', statusCode: undefined }
```

or this is should be `undefined` as they are?

**Comment by transitive-bullshit** [comment]
We will only have a `statusCode` if `got` returns an [error](https://github.com/sindresorhus/got#errors) that contains a `statusCode`. There will be some cases where the specific `statusCode` isn't available because the network or DNS failed to connect.

**Comment by l2aelba** [comment]
Aha! I forgot to think about this! @transitive-bullshit

Closed.
