### ISSUE TITLE
Pass options to `got`

### ISSUE THREAD

**Issue by wooorm** [transitive-bullshit/check-links#5]
The docs mention:

> `opts` `object?` Optional configuration options (any extra options are passed to got)

…but [there is only code that mixes `opts.headers` with the default headers](https://github.com/transitive-bullshit/check-links/blob/0d135df3411e7148d9c0fdf8dccc2ceac2962085/lib/check-link.js#L26-L39).

Based on the docs, [`remark-lint-no-dead-urls`](https://github.com/davidtheclark/remark-lint-no-dead-urls#options) has `gotOptions`, but they’re not working (davidtheclark/remark-lint-no-dead-urls#15).

Can other options also be passed through to got?

**Comment by transitive-bullshit** [comment]
Yep; this looks like a bug. I'll have some time to address it likely Tuesday.

If anyone wants to submit a PR before then, feel free.

Thanks! 😄

**Comment by transitive-bullshit** [comment]
This should be fixed via https://github.com/transitive-bullshit/check-links/commit/6ed05365100adb9ee1b2a62d0a01b961408cb32a and released as a patch `v1.1.8`.

**Comment by wooorm** [comment]
Sweet, thanks! Closing as it’s probably done!
